## CVIT Summer School 2020

Day 06 (Morning Session): Iris Dataset Classification using kNN
    
Instructor: Chris Andrew Gadde

### A Brief History

This is a multivariate dataset introduced by R.A.Fisher (Father of Modern Statistics) for showcasing linear discriminant analysis. This is arguably the best known dataset in Feature Selection literature.

The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant. One class is linearly separable from the other 2; the latter are NOT linearly separable from each other.

### Description

The Iris dataset consists of 150 data instances. There are 3 classes (Iris Versicolor, Iris Setosa and Iris Virginica) each have 50 instances.

For each flower we have the below data attributes

- sepal length in cm
- sepal width in cm
- petal length in cm
- petal width in cm

To make our experiment easy we rename the classes with numbers :

- "0": setosa
- "1": versicolor
- "2": virginica

### Challenges

When we use the data with large number of features or dimensionality, models usually choke because:

1. Training time increases exponentially with number of features.
2. Models have increasing risk of overfitting with increasing number of features.

To avoid the above mentioned problems while learning about data analysis, we use simple, well behaved, data that reduces the cognitive load, and makes it easier to debug as we are able to better comprehend the data we are working with.

Hence, this is a good dataset to work on.

### Domain Information

Iris Plants are flowering plants with showy flowers. They are very popular among movie directors as it gives excellent background.

They are predominantly found in dry, semi-desert, or colder rocky mountainous areas in Europe and Asia. They have long, erect flowering stems and can produce white, yellow, orange, pink, purple, lavender, blue or brown colored flowers. There are 260 to 300 types of iris.

### Setup

In [5]:
#@title Run this cell to complete the setup for this Notebook
from IPython import get_ipython

ipython = get_ipython()

ipython.magic("sx apt-get install graphviz")
ipython.magic("sx pip install graphviz")

['Collecting graphviz',
 '  Downloading graphviz-0.14-py2.py3-none-any.whl (18 kB)',
 'Installing collected packages: graphviz',
 'Successfully installed graphviz-0.14']

### Import Required Packages

In [6]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

### Load the Data

In [7]:
# Load data
iris = load_iris()

In [8]:
# Checking for the type of iris
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [9]:
# Checking the keys
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [10]:
# Checking for the type of data
print(type(iris.data))

<class 'numpy.ndarray'>


In [11]:
# Checking for unique target or class values
print(set(iris.target))

{0, 1, 2}


In [12]:
# Let us see how the iris data looks
print(iris.data[::15])

[[5.1 3.5 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.8 3.1 1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.5 2.6 4.4 1.2]
 [7.6 3.  6.6 2.1]
 [6.9 3.2 5.7 2.3]
 [7.7 3.  6.1 2.3]]


In [13]:
# Let us see how the labels 
print(iris.target[::15])

[0 0 0 0 1 1 1 2 2 2]


In [14]:
# Storing the data and labels into "X" and "y" varaibles
X = iris.data
y = iris.target

### Splitting the Data into Train and Test Sets

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
# Training and testing set ratio is 70 : 30
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
# Let us see the size of train and  test sets
X_train.shape, X_test.shape

((100, 4), (50, 4))

In [18]:
# Let us see first five rows of the training data
X_train[:5]

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ]])

### Train a kNN Classifier

In [20]:
from sklearn.neighbors import KNeighborsClassifier

In [21]:
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,y_train)
y_pred = neigh.predict(X_test)
score = (y_pred == y_test).sum()/len(y_test)
score2 = neigh.score(X_test,y_test)
print(score, score2)

0.98 0.98


### Exercise: Plot Accuracy vs #Neighbours Graph